### ISSUE TITLE
OPENELEC树莓派脚本错误

### ISSUE THREAD

**Issue by Moelf** [Syndim/XBMC-Bilibili#5]
不强求了毕竟是树莓派
log：http://xbmclogs.com/show.php?id=254062

似乎出错在3280行 _print_info为什么没找到

**Comment by Syndim** [comment]
fixed

另外我看log似乎还有一些其他的问题，我自己在windows上试了下是可以播放的，等我有空了来研究一下log。

**Comment by Moelf** [comment]
我在Debian xbmc上，上一个commit就可以播放，所以我觉得是opebelec的问题，我回去试试再看，辛苦啦w

**Comment by Moelf** [comment]
openelec

**Comment by Moelf** [comment]
经验证， openlelc上应该是另一个问题， 你之后有空再看看吧
